### ISSUE TITLE
No colors on iOS 14.4

### ISSUE THREAD

**Issue by Brandon-Gottshall** [scarnett/flutter_weather#65]
![876E86FA-CCDC-47A4-9B6C-EBFDFC529B5E](https://user-images.githubusercontent.com/55668392/110179967-f6155a80-7dd6-11eb-88ca-750246d083b1.png)
![8A1ADF5D-78F0-4671-AAC1-5775E6EB79B0](https://user-images.githubusercontent.com/55668392/110179968-f6adf100-7dd6-11eb-895d-0786baca978b.png)
![7BF88530-DBA8-4F65-A51E-94B6404F5BD6](https://user-images.githubusercontent.com/55668392/110179969-f7468780-7dd6-11eb-97af-0375996018d0.png)
![7534782F-8F6C-4221-BB9C-BE672EC4D526](https://user-images.githubusercontent.com/55668392/110179971-f7468780-7dd6-11eb-9062-fb5487c01c6b.png)

**Comment by scarnett** [comment]
Hey Brandon, I did notice a small issue in the current version so I pushed a fix and am awaiting approval from Apple for its release. Does anything happen when you tap the 'brightness' icon to the left of the light / dark switch? This icon is what toggles the color theme mode.
